### ISSUE TITLE
Issue on the Lectures, Tutorials and Webinars widget

### ISSUE THREAD

**Issue by SophieMacadamia** [IS-ENES3/IS-ENES-Website#8]
Hi, I've added one widget to the "Lectures, Tutorials and Webinars" page (the last widget, entitled "6th Coupling Workshop" and the picture ("Coupled-Systems-I.png") does not appear on the webpage: https://is.enes.org/lectures-tutorials-webinars/
Where does that come from ? 
Thanks !

**Comment by valeriupredoi** [comment]
Hi @SophieMacadamia you widget is:
```
widget11:
  title: "6th Coupling Workshop (2023)"
  url: 'https://www.youtube.com/watch?v=9dK_BP6LXZM&list=PLFvev1W5vG7NVX4AMbERCgMfEe--wTUMN&ab_channel=IS-ENES3H2020'
  image: 'Coupled-Systems-I.png'
  text: '6th Workshop on Coupling Technologies for Earth System Models, Toulouse, January 2023'
```

so it needs Coupled-Systems-I.png in images/ - I just had a look and there's no such png there, just plop it in there :smiley:
